@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

BlockBook *-right-> "1" UniqueGamerList
BlockBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueGamerList
UniqueTagList -[hidden]down- UniqueGamerList

UniqueTagList -right-> "*" Tag
UniqueGamerList -right-> Gamer

Gamer -up-> "*" Tag

Gamer *--> Name
Gamer *--> Phone
Gamer *--> Email
Gamer *--> Address
@enduml

